language: go
env:
- GO111MODULE=on
go:
- 1.12.5
install: true
script:
- "./lifecycle/build.sh"
deploy:
  provider: releases
  api_key:
    secure: RshtEyr+wTbiQx7q5DF7e8118wBqiGDMNNzUIgF93sToNa/EOUW/DHeCDZayK45N+vqfqgEN0+XAh6pVmg06hB3+UPtxE/Z/sznGkZJ1oebwNIjtEfuoSBL5dBw4MNEIF2yLIDQy7OS/A7iHfeY4uaAUbXtOLd3KWKF6LphcJilSkkNhgtF4Eh12hHh95rf/EVTSQHMEE17SY0EZTOnc/5s71Y3O4huWgmtVZkmTqakg1yOHFUQTfO9ttPgiCiiobWkXGzpzQnFbc3kNiaC+tlUyXWtlCwJmdqk2jM09dxVZ/RYqqmzoPopmA+bj3kzCCLThJjRf5vqP2SnuGByDdFh2GZBiopRU/TN88k7GWmpzIEhle90SJknTaYTOMKMGN/Oes58HHDw7RA99D7lTtMj6fM83KL5IiXhgZM+Ew6SgyYV0wTpCJ17xs5F7Ftn5FHjyPJJdjjcasbOlIlfxqJ9GDnMTjYM/U2/wCiQMmUo+JKg3XbSSmQaFMKcWlU8JD9EArhsD/zzEj91YhPQmjY0CHIPW92TiBGGj0UamMvC/LlpU5mKgmnMqqatWX5vq5ZqeFIIwUxBGxaiyHb2EvkDsqZ+BOX6pWWXIPzUgcEdoy9j2EaS/EmA9zvO+rAlyZpB9BNTAUrqpj19Nd/ofBqDKeLqamK5LRYFAaHv8ZDo=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: Nike-Inc/cerberus-cli
