name: Build and Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          go test -v ./client ./cmd ./tool -coverprofile=coverage.txt -covermode=atomic
      - name: build
        run: ./lifecycle/build.sh
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: go/src/cerberus-go-client/coverage.txt # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true
      - name: Upload binary to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/cerberus-cli-darwin-amd64
          tag: ${{ github.ref }}
      - name: Upload binary to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/cerberus-cli-linux-amd64
          tag: ${{ github.ref }}
      - name: Upload binary to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/cerberus-cli-windows-amd64.exe
          tag: ${{ github.ref }}
      - name: Slack notification when master build fails
        if: ${{ failure() && github.ref == 'refs/heads/master'}}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cerberus-alerts
          SLACK_MESSAGE: 'Cerberus main build has failed :build-failed:'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Cerberus Build Failure Notification
          SLACK_USERNAME: GitHub Actions